# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-09-01 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='id',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='folio',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
