# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-09-02 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default=0, upload_to='photos'),
            preserve_default=False,
        ),
    ]
