# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-09-03 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_remove_persona_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
